In [4]:
import numpy as np

In [5]:
a = np.arange(1,50).reshape((7,7))

In [6]:
a

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19, 20, 21],
       [22, 23, 24, 25, 26, 27, 28],
       [29, 30, 31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40, 41, 42],
       [43, 44, 45, 46, 47, 48, 49]])

In [8]:
a[::2, ::]

array([[ 1,  2,  3,  4,  5,  6,  7],
       [15, 16, 17, 18, 19, 20, 21],
       [29, 30, 31, 32, 33, 34, 35],
       [43, 44, 45, 46, 47, 48, 49]])

In [10]:
a[::3, ::3]

array([[ 1,  4],
       [22, 25],
       [43, 46]])

In [11]:
b = a[a %2 == 0]

In [12]:
b

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34,
       36, 38, 40, 42, 44, 46, 48])

In [13]:
b.sum()

600

In [14]:
b.var()

191.66666666666666

In [15]:
b.std()

13.844373104863458

In [17]:
b.ndim

1

In [18]:
b.shape

(24,)