In [1]:
import numpy as np

In [2]:
np.ones(2)

array([1., 1.])

In [3]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [5]:
np.ones((2,3), dtype = 'int8')

array([[1, 1, 1],
       [1, 1, 1]], dtype=int8)

In [6]:
np.ones((2,3,3))

array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]])

In [ ]:
np.zeros(2)

In [9]:
np.eye(2)

array([[1., 0.],
       [0., 1.]])

In [10]:
np.eye(5,4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.]])

In [11]:
np.eye(5,4, dtype='int8',k=1)

array([[0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1],
       [0, 0, 0, 0],
       [0, 0, 0, 0]], dtype=int8)

k=1 moves the no of 1's to the upper diagonal and k=-1 moves the no of 1's to the lower diagonal

np.eye is a psuedo identity matrix, which puts 1's in the diagonal and 0's in other 

In [12]:
np.identity(2, dtype='int8')

array([[1, 0],
       [0, 1]], dtype=int8)

np.full() it returns a new return type with fill value

In [13]:
np.full(5,10)

array([10, 10, 10, 10, 10])

np.full takes two arguments shape and fill_value

5 means row and 10 means fill the 5 rows with 10 

In [14]:
np.full((5,3),10)

array([[10, 10, 10],
       [10, 10, 10],
       [10, 10, 10],
       [10, 10, 10],
       [10, 10, 10]])

giving rows and column in a tuple makes it a 2D array

In [15]:
np.empty((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

np.empty gives a shape and gives out random value


In [17]:
np.empty((3,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [19]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [20]:
np.linspace(10,50)

array([10.        , 10.81632653, 11.63265306, 12.44897959, 13.26530612,
       14.08163265, 14.89795918, 15.71428571, 16.53061224, 17.34693878,
       18.16326531, 18.97959184, 19.79591837, 20.6122449 , 21.42857143,
       22.24489796, 23.06122449, 23.87755102, 24.69387755, 25.51020408,
       26.32653061, 27.14285714, 27.95918367, 28.7755102 , 29.59183673,
       30.40816327, 31.2244898 , 32.04081633, 32.85714286, 33.67346939,
       34.48979592, 35.30612245, 36.12244898, 36.93877551, 37.75510204,
       38.57142857, 39.3877551 , 40.20408163, 41.02040816, 41.83673469,
       42.65306122, 43.46938776, 44.28571429, 45.10204082, 45.91836735,
       46.73469388, 47.55102041, 48.36734694, 49.18367347, 50.        ])

In [22]:
np.linspace(10,50, endpoint=False, num=51, retstep=True) 

(array([10.        , 10.78431373, 11.56862745, 12.35294118, 13.1372549 ,
        13.92156863, 14.70588235, 15.49019608, 16.2745098 , 17.05882353,
        17.84313725, 18.62745098, 19.41176471, 20.19607843, 20.98039216,
        21.76470588, 22.54901961, 23.33333333, 24.11764706, 24.90196078,
        25.68627451, 26.47058824, 27.25490196, 28.03921569, 28.82352941,
        29.60784314, 30.39215686, 31.17647059, 31.96078431, 32.74509804,
        33.52941176, 34.31372549, 35.09803922, 35.88235294, 36.66666667,
        37.45098039, 38.23529412, 39.01960784, 39.80392157, 40.58823529,
        41.37254902, 42.15686275, 42.94117647, 43.7254902 , 44.50980392,
        45.29411765, 46.07843137, 46.8627451 , 47.64705882, 48.43137255,
        49.21568627]),
 0.7843137254901961)

In [23]:
from numpy import random

In [24]:
random.randint(1,10)

2

In [26]:
random.randint(10)

1

reset and 3D slicing in numpy

In [27]:
a = np.array([1,2,3,5.1])

In [28]:
a

array([1. , 2. , 3. , 5.1])

this is called upcasting, the numpy array searches for the higher data types for eg: float here and upcasts the int to float

downcasting can also be done however it is not done because the data is lost

In [29]:
from matplotlib import pyplot