In [1]:
import numpy as np

In [2]:
a = np.array([1,2,3])

In [3]:
b = np.array([4,5,6])

In [4]:
np.concatenate((a,b))

array([1, 2, 3, 4, 5, 6])

In [9]:
a = np.arange(1,10).reshape((3,3))

In [10]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [11]:
b = np.arange(10,19).reshape((3,3))

axis = 0, row increases (vertically)

In [12]:
np.concatenate((a,b))

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

axis = 1, column increases (horizontally)

In [13]:
np.concatenate((a,b), axis=1)

array([[ 1,  2,  3, 10, 11, 12],
       [ 4,  5,  6, 13, 14, 15],
       [ 7,  8,  9, 16, 17, 18]])

stack, if we add 1D 1D element then dimension increases

In [14]:
np.stack((a,b))

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [15]:
a = np.arange(4)

In [16]:
a

array([0, 1, 2, 3])

In [17]:
b = np.arange(4,8)

In [18]:
b

array([4, 5, 6, 7])

In [19]:
np.stack((a,b))

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [20]:
np.stack((a,b), axis=1)

array([[0, 4],
       [1, 5],
       [2, 6],
       [3, 7]])

Condition based selection is a[a%2==0]

In [21]:
np.where(a%2==0)

(array([0, 2]),)

In [22]:
np.sort(a)

array([0, 1, 2, 3])

In [24]:
a = np.random.randint(0,25,(5,5))

In [25]:
a

array([[ 1, 15,  3, 17, 19],
       [ 8,  0,  5,  9, 12],
       [24, 23, 22,  0, 20],
       [12, 16,  4, 24, 11],
       [18,  3,  2,  2, 13]])

In [26]:
np.sort(a)

array([[ 1,  3, 15, 17, 19],
       [ 0,  5,  8,  9, 12],
       [ 0, 20, 22, 23, 24],
       [ 4, 11, 12, 16, 24],
       [ 2,  2,  3, 13, 18]])

1D slicing

In [27]:
a[0,0]

1

In [28]:
a[0:5, 0]

array([ 1,  8, 24, 12, 18])

This is 2D slicing

In [29]:
a[0:5, 0:1]

array([[ 1],
       [ 8],
       [24],
       [12],
       [18]])

This gives out random values, it is called fancy or advanced indexing

In [36]:
c =np.arange(10)

In [39]:
c[0]= 500

In [40]:
c[[0,6,8]]

array([500,   6,   8])

In [43]:
c[[True, False, False, False, False, False, True, False,True, False]]

array([500,   6,   9])

view

In [30]:
a = np.arange(10)

In [31]:
b = a.view()

In [32]:
b

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [33]:
id(a)

4446984112

In [34]:
id(b)

4446985840

id of a and b is different because b is a pointer of a.
so it stores the address of b
when b is modified, a is also modified.

shallow copy: pass by value
deep copy: pass by reference