In [1]:
import numpy as np

In [2]:
np.ones(2)

array([1., 1.])

In [9]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [4]:
np.ones((2,3),  dtype='int8')

array([[1, 1, 1],
       [1, 1, 1]], dtype=int8)

In [5]:
np.ones((2,3,3))

array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]])

In [8]:
np.zeros(2)

array([0., 0.])

In [2]:
a = np.zeros((2,3))

In [3]:
a.nbytes

48

In [4]:
b = np.zeros((2,3), dtype='int8')

In [5]:
b.nbytes

6

In [16]:
np.eye(5,4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.]])

In [17]:
np.eye(5,4, dtype='int8') 

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1],
       [0, 0, 0, 0]], dtype=int8)

In [6]:
np.eye(3,2, dtype='int8', k=1)

array([[0, 1],
       [0, 0],
       [0, 0]], dtype=int8)

In [19]:
np.eye(5,4, dtype='int8', k=-1)

array([[0, 0, 0, 0],
       [1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]], dtype=int8)

In [21]:
np.identity(2, dtype='int8')

array([[1, 0],
       [0, 1]], dtype=int8)

In [22]:
np.identity(2, dtype=np.int8)

array([[1, 0],
       [0, 1]], dtype=int8)

In [25]:
np.full((5,3), 10)

array([[10, 10, 10],
       [10, 10, 10],
       [10, 10, 10],
       [10, 10, 10],
       [10, 10, 10]])

In [38]:
np.empty((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [39]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [40]:
np.arange(2,10)

array([2, 3, 4, 5, 6, 7, 8, 9])

In [41]:
np.arange(2,10,3)

array([2, 5, 8])

In [50]:
np.linspace(10,60, endpoint=True, num=10, retstep=True)

(array([10.        , 15.55555556, 21.11111111, 26.66666667, 32.22222222,
        37.77777778, 43.33333333, 48.88888889, 54.44444444, 60.        ]),
 5.555555555555555)

In [7]:
from numpy.random import randint

In [8]:
np.random.randint(5, size=10)

array([4, 2, 3, 2, 4, 3, 2, 3, 2, 2])

In [58]:
np.random.randint(5, size=10)

array([1, 3, 1, 1, 2, 4, 2, 1, 4, 0])

In [61]:
np.random.randint(5, 10, size=10)

array([7, 5, 8, 8, 5, 8, 6, 7, 7, 8])

In [9]:
a = np.array([1,2,3,4,5.1])

In [10]:
a

array([1. , 2. , 3. , 4. , 5.1])

In [66]:
a = np.array([1,2,3,4,5.1, 'a'])

In [67]:
a

array(['1', '2', '3', '4', '5.1', 'a'], dtype='<U32')

In [68]:
a = np.array([1,2,3,4,5.1], dtype='int8')

In [69]:
a

array([1, 2, 3, 4, 5], dtype=int8)

In [11]:
from matplotlib import pyplot

In [ ]:
a = pyplot.imread('dog.jpeg')

In [73]:
a.shape

(318, 318, 3)

In [74]:
a = np.ones((2,3))

In [75]:
a

array([[1., 1., 1.],
       [1., 1., 1.]])

In [76]:
a.shape

(2, 3)

In [77]:
a.size

6

In [78]:
a.dtype

dtype('float64')

In [79]:
a.ndim

2

In [80]:
a.nbytes

48

In [81]:
a.itemsize

8