In [1]:
import numpy as np

In [5]:
a = np.arange(9)

In [6]:
b = a

In [7]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [8]:
b

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [9]:
b[0] = 100

In [10]:
b

array([100,   1,   2,   3,   4,   5,   6,   7,   8])

In [11]:
a

array([100,   1,   2,   3,   4,   5,   6,   7,   8])

In [12]:
a[3] = 100

In [13]:
a

array([100,   1,   2, 100,   4,   5,   6,   7,   8])

In [14]:
b

array([100,   1,   2, 100,   4,   5,   6,   7,   8])

In [18]:
a = np.array([1, 2, 3, 4, 5, 6, 7, 8])

In [19]:
a

array([1, 2, 3, 4, 5, 6, 7, 8])

In [20]:
b = a.copy()

In [21]:
b[0] = 100

In [22]:
b

array([100,   2,   3,   4,   5,   6,   7,   8])

In [23]:
a

array([1, 2, 3, 4, 5, 6, 7, 8])

In [24]:
a = np.arange(10)

In [25]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [26]:
b = a[3:6]

In [27]:
b

array([3, 4, 5])

In [28]:
b[0] = 100

In [29]:
a

array([  0,   1,   2, 100,   4,   5,   6,   7,   8,   9])

In [24]:
a[[1,3,8]]

array([  1, 100,   8])

In [25]:
a 

array([  0,   1,   2, 100,   4,   5,   6,   7,   8,   9])

In [2]:
a = np.arange(12)

In [3]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [28]:
int(1.1)

1

In [29]:
1/1

1.0

In [30]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [4]:
np.reshape(a, (4,3))

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11]])

In [32]:
np.reshape(a, (6,2))

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]])

In [33]:
np.reshape(a, (6,3))

ValueError: cannot reshape array of size 12 into shape (6,3)

In [34]:
np.reshape(a, (6,1))

ValueError: cannot reshape array of size 12 into shape (6,1)

In [6]:
np.reshape(a, (6,-3))

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]])

In [7]:
np.reshape(a, (-4, 6))

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

In [37]:
np.reshape(a, (-1,-1))

ValueError: can only specify one unknown dimension

In [8]:
b = np.reshape(a, (-1, 6))

In [9]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [10]:
b

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

In [11]:
b[0] = 12

In [12]:
a

array([12, 12, 12, 12, 12, 12,  6,  7,  8,  9, 10, 11])

In [43]:
len('umesh')

5

In [44]:
'umesh'.upper()

'UMESH'

In [46]:
b = np.resize(a, (2,2))

In [13]:
c = np.resize(a, (4,4))

In [14]:
c

array([[12, 12, 12, 12],
       [12, 12,  6,  7],
       [ 8,  9, 10, 11],
       [12, 12, 12, 12]])

In [4]:
a = np.array([1,2,3,4,5,6,7,8])

In [19]:
a

array([1, 2, 3, 4, 5, 6, 7, 8])

In [20]:
b = np.resize(a, (4,4))

In [21]:
a

array([1, 2, 3, 4, 5, 6, 7, 8])

In [5]:
a.resize((4,4), refcheck=False)

In [6]:
a

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [47]:
b = a.T

In [48]:
b

array([[1, 5, 0, 0],
       [2, 6, 0, 0],
       [3, 7, 0, 0],
       [4, 8, 0, 0]])

In [7]:
b = np.ravel(a)

In [8]:
a

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [51]:
b

array([1, 2, 3, 4, 5, 6, 7, 8, 0, 0, 0, 0, 0, 0, 0, 0])

In [9]:
b[0] = 100

In [10]:
a

array([[100,   2,   3,   4],
       [  5,   6,   7,   8],
       [  0,   0,   0,   0],
       [  0,   0,   0,   0]])

In [54]:
a

array([[100,   2,   3,   4],
       [  5,   6,   7,   8],
       [  0,   0,   0,   0],
       [  0,   0,   0,   0]])

In [11]:
b = a.flatten()

In [12]:
b

array([100,   2,   3,   4,   5,   6,   7,   8,   0,   0,   0,   0,   0,
         0,   0,   0])

In [13]:
b[1] = 1212 

In [14]:
a

array([[100,   2,   3,   4],
       [  5,   6,   7,   8],
       [  0,   0,   0,   0],
       [  0,   0,   0,   0]])

In [15]:
b

array([ 100, 1212,    3,    4,    5,    6,    7,    8,    0,    0,    0,
          0,    0,    0,    0,    0])

In [75]:
np.ravel(a, order='F')

array([100,   5,   0,   0,   2,   6,   0,   0,   3,   7,   0,   0,   4,
         8,   0,   0])