In [1]:
import numpy as np

In [2]:
a = np.array([[1,2,3,4,5], [6,7,8,9,10]])

In [3]:
a[0]

array([1, 2, 3, 4, 5])

In [4]:
a[1]

array([ 6,  7,  8,  9, 10])

In [5]:
for item in a:
    print(item)

[1 2 3 4 5]
[ 6  7  8  9 10]


In [6]:
for row in a:
    for item in row:
        print(item)

1
2
3
4
5
6
7
8
9
10


In [9]:
for item in np.nditer(a):
    print(item)

1
2
3
4
5
6
7
8
9
10


In [10]:
a = ['umesh', 'ram', 'shyam', 'hari']

In [11]:
for item in a:
    print(item)

umesh
ram
shyam
hari


In [12]:
for item in enumerate(a):
    print(item)

(0, 'umesh')
(1, 'ram')
(2, 'shyam')
(3, 'hari')


In [13]:
i, j = (1,2)

In [12]:
i

1

In [13]:
j

2

In [7]:
i = (1,2)

In [14]:
for k,v in enumerate(a):
    print(k,v)

0 umesh
1 ram
2 shyam
3 hari


In [15]:
a = np.array([[1,2,3,4,5], [6,7,8,9,10]])

In [16]:
for item in np.ndenumerate(a):
    print(item)

((0, 0), 1)
((0, 1), 2)
((0, 2), 3)
((0, 3), 4)
((0, 4), 5)
((1, 0), 6)
((1, 1), 7)
((1, 2), 8)
((1, 3), 9)
((1, 4), 10)


In [17]:
a = [1,2,3,4] 
b = [5,6,7,8]

In [18]:
a + b

[1, 2, 3, 4, 5, 6, 7, 8]

In [19]:
a = np.array([1,2,3,4])
b = np.array([5,6,7,8])

In [20]:
a

array([1, 2, 3, 4])

In [21]:
b

array([5, 6, 7, 8])

In [22]:
a + b

array([ 6,  8, 10, 12])

In [23]:
a + 5

array([6, 7, 8, 9])

In [24]:
a = np.array([1000, 2000, 2500, 3200])

In [25]:
a

array([1000, 2000, 2500, 3200])

In [26]:
a + 5000

array([6000, 7000, 7500, 8200])

In [27]:
a * 5

array([ 5000, 10000, 12500, 16000])

In [28]:
a ** 2

array([ 1000000,  4000000,  6250000, 10240000])

In [29]:
a.mean()

2175.0

In [30]:
a.sum()

8700

In [31]:
a.std()

801.1710179481032

In [32]:
a.var()

641875.0

In [33]:
a = np.array(['umesh', 'regmi', 'ram', 'shyam', 'hari', 'rita', 'sita'])

In [34]:
a[0]

'umesh'

In [54]:
a[1]

'regmi'

In [55]:
a[2]

'ram'

In [35]:
a[[1,2,3]]

array(['regmi', 'ram', 'shyam'], dtype='<U5')

In [36]:
a[[True, False, True, False, False, False, False]]

array(['umesh', 'ram'], dtype='<U5')

In [37]:
a = np.array([10,11,12,13,14,15,16])

In [38]:
a[[True, False, True, False, False, False, False]]

array([10, 12])

In [39]:
a > 14

array([False, False, False, False, False,  True,  True])

In [40]:
a % 2 == 0

array([ True, False,  True, False,  True, False,  True])

In [41]:
a[[ True, False,  True, False,  True, False,  True]]

array([10, 12, 14, 16])

In [42]:
a[a % 2 == 0]

array([10, 12, 14, 16])

In [43]:
a[a >= 13]

array([13, 14, 15, 16])

In [44]:
a[(a >=12) & (a <= 14)]

array([12, 13, 14])

In [45]:
a[(a == 12) | (a == 14)]

array([12, 14])

In [46]:
a[(a <= 12) | (a >= 14)]

array([10, 11, 12, 14, 15, 16])

In [47]:
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])

In [48]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [83]:
a[[0]]

array([[1, 2, 3, 4]])

In [84]:
a[0][1]

2

In [85]:
a[2][2]

11

In [86]:
a[2,2]

11

In [87]:
a[0:2]

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [49]:
a = np.arange(1, 50).reshape((7,7))

In [50]:
a

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19, 20, 21],
       [22, 23, 24, 25, 26, 27, 28],
       [29, 30, 31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40, 41, 42],
       [43, 44, 45, 46, 47, 48, 49]])

In [51]:
a[::2]

array([[ 1,  2,  3,  4,  5,  6,  7],
       [15, 16, 17, 18, 19, 20, 21],
       [29, 30, 31, 32, 33, 34, 35],
       [43, 44, 45, 46, 47, 48, 49]])

In [52]:
a[0:3 , 1:3]

array([[ 2,  3],
       [ 9, 10],
       [16, 17]])

In [53]:
a[3:5, 1:3]

array([[23, 24],
       [30, 31]])

In [93]:
a[3:, 1:3]

array([[16, 17],
       [21, 22]])

In [94]:
a[::2, ::2]

array([[ 0,  2,  4],
       [10, 12, 14],
       [20, 22, 24]])

In [96]:
a = np.arange(1, 50).reshape((7,7))

In [97]:
a

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19, 20, 21],
       [22, 23, 24, 25, 26, 27, 28],
       [29, 30, 31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40, 41, 42],
       [43, 44, 45, 46, 47, 48, 49]])

In [100]:
a[::2, ::]

array([[ 1,  2,  3,  4,  5,  6,  7],
       [15, 16, 17, 18, 19, 20, 21],
       [29, 30, 31, 32, 33, 34, 35],
       [43, 44, 45, 46, 47, 48, 49]])

In [101]:
a[::3, ::3]

array([[ 1,  4,  7],
       [22, 25, 28],
       [43, 46, 49]])

In [54]:
b = a[a % 2 == 0]

In [55]:
b

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34,
       36, 38, 40, 42, 44, 46, 48])

dimension, shape, size, bytes, sum, min max mean var std

In [56]:
b.ndim

1

In [108]:
b.shape

(24,)

In [109]:
b.size

24

In [111]:
b.itemsize

4

In [112]:
b.nbytes

96

In [113]:
b.sum()

600

In [114]:
b.max()

48

In [115]:
b.min()

2

In [116]:
b.mean()

25.0

In [117]:
b.std()

13.844373104863458

In [118]:
b.var()

191.66666666666666

In [119]:
b.dtype

dtype('int32')